baseURL = "http://graememyers.com"
title = "Graeme Myers"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

[params]
author = "Graeme Myers"
description = "Graeme Myers Personal Site"
keywords = "academic,developer,personal"
info = ["MA Candidate - Comparative Literature & Jewish Studies", "University of Toronto"]
avatarURL = "images/graememyers.jpg"
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.cdn.hbchan.top/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
# siteID = "ABCDE"
# serverURL = "analytics.example.com" # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
# domain = "example.com"
# serverURL = "analytics.example.com" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]
# code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Matomo(https://matomo.org) for analytics, add this section
# [params.matomo]
# siteID = "ABCDE" # Default value is "1", overwrite this if you are cloud-hosting
# serverURL = "analytics.example.com" # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

# If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
# [params.googleTagManager]
# id = "gid"

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
  childsrc = ["'self'"]
  fontsrc = [
    "'self'",
    "https://fonts.gstatic.com",
    "https://cdn.jsdelivr.net/"
  ]
  formaction = ["'self'"]
  framesrc = ["'self'"]
  imgsrc = ["'self'"]
  objectsrc = ["'none'"]
  stylesrc = [
    "'self'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com/",
    "https://cdn.jsdelivr.net/"
  ]
  scriptsrc = [
    "'self'",
    "'unsafe-inline'",
    "https://www.google-analytics.com"
  ]
  prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.cdn.hbchan.top/gmyers7/"

[languages.en]
languageName = ":canada:"
weight = 1
contentDir = "content/english"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "CV"
weight = 2
url = "cv/"

[[languages.en.menu.main]]
name = "Publications"
weight = 3
url = "publications/"

[[languages.en.menu.main]]
name = "Contact"
weight = 4
url = "contact/"

[languages.es]
languageName = ":argentina:"
weight = 2
title = "Graeme Myers"
contentDir = "content/spanish"

[languages.es.params]
author = "Graeme Myers"
info = "Candidato de Magistre, Literatura Comparativa e Estudios Judíos - Universidad de Toronto"
description = "Sítio personal de Graeme Myers"
keywords = "academic,desarrollador,personal"

[[languages.es.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.es.menu.main]]
name = "CV"
weight = 2
url = "cv/"

[[languages.es.menu.main]]
name = "Publicaciones"
weight = 3
url = "publications/"

[[languages.es.menu.main]]
name = "Contacto"
weight = 5
url = "contact/"

[languages.pt]
languageName = ":brazil:"
weight = 3
title = "Graeme Myers"
contentDir = "content/portuguese"

[languages.pt.params]
author = "Graeme Myers"
info = "Candidato a Mestrado, Literatura Comparativa e Estudos Judaicos - Universidade de Toronto"
description = "Sítio pessoal de Graeme Myers"
keywords = "academic,desenvolvedor,pessoal"

[[languages.pt.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.pt.menu.main]]
name = "CV"
weight = 2
url = "cv/"

[[languages.pt.menu.main]]
name = "Publicações"
weight = 3
url = "publications/"

[[languages.pt.menu.main]]
name = "Contato"
weight = 5
url = "contact/"

[languages.yi]
languagedirection = 'rtl'
languageName = ":israel:"
weight = 4
title = "גרײעם מײַערס"
contentDir = "content/yiddish"

[languages.yi.params]
author = "גרײעם מײַערס"
info = "Candidato a Mestrado, Literatura Comparativa e Estudos Judaicos - Universidade de Toronto"
description = "Sítio pessoal de Graeme Myers"
keywords = "academic,desenvolvedor,pessoal"

[[languages.yi.menu.main]]
name = "װעגן איך"
weight = 1
url = "about/"

[[languages.yi.menu.main]]
name = "רעזומע"
weight = 2
url = "cv/"

[[languages.yi.menu.main]]
name = "פּובליקאַציעס"
weight = 3
url = "publications/"

[[languages.yi.menu.main]]
name = "קאָנטאַקטירן"
weight = 5
url = "contact/"
